local D=require('editor_support.document')
local J=require('editor_support.json')
local S={}
function S.slug(name)
  local value=name:lower():gsub('[^a-z0-9]+','-'):gsub('^-',''):gsub('-$',''):sub(1,64)
  return value~='' and value or 'effect'
end
function S.decode(text) return D.validate(J.decode(text)) end
function S.write(path,text)
  assert(path:match('^[a-z]+/[a-z0-9%-]+%.[a-z]+$'),'Invalid project destination.')
  assert(love.filesystem.createDirectory(path:match('^([^/]+)')))
  local ok,err=love.filesystem.write(path..'.tmp',text);assert(ok,err)
  local root=love.filesystem.getSaveDirectory()..'/'
  ok,err=os.rename(root..path..'.tmp',root..path)
  if not ok and love.filesystem.getInfo(path,'file') then
    -- Windows does not replace an existing destination. Keep the previous file recoverable.
    love.filesystem.remove(path..'.bak')
    local backedUp,backupError=os.rename(root..path,root..path..'.bak')
    assert(backedUp,backupError)
    ok,err=os.rename(root..path..'.tmp',root..path)
    if not ok then os.rename(root..path..'.bak',root..path) end
  end
  assert(ok,err)
  return root..path
end
function S.save(doc)
  D.validate(doc)
  local path='projects/'..S.slug(doc.name)..'.json'
  if love.filesystem.getInfo(path,'file') then
    local ok,existing=pcall(S.decode,love.filesystem.read(path))
    assert(ok and existing.name==doc.name,'Another project uses this file name. Rename the composition before saving.')
  end
  return S.write(path,J.encode(doc))
end
function S.load(file)
  assert(file:match('^[a-z0-9%-]+%.json$'),'Invalid project name.')
  return S.decode(assert(love.filesystem.read('projects/'..file)))
end
function S.list()
  local out={}
  if love.filesystem.getInfo('projects','directory') then
    for _,name in ipairs(love.filesystem.getDirectoryItems('projects')) do if name:match('^[a-z0-9%-]+%.json$') then out[#out+1]=name end end
  end
  table.sort(out);return out
end
local function lua(value,depth)
  depth=depth or 0
  if type(value)=='string' then return string.format('%q',value)
  elseif type(value)=='number' then return string.format('%.17g',value)
  elseif type(value)=='boolean' then return tostring(value) end
  assert(type(value)=='table','Cannot export this value.')
  local keys={};for k in pairs(value) do keys[#keys+1]=k end
  table.sort(keys,function(a,b) return tostring(a)<tostring(b) end)
  local out={'{'}
  for _,k in ipairs(keys) do out[#out+1]=string.rep(' ',depth+2)..'['..lua(k)..']='..lua(value[k],depth+2)..',' end
  out[#out+1]=string.rep(' ',depth)..'}';return table.concat(out,'\n')
end
function S.exportSource(doc)
  D.validate(doc)
  local runtime=assert(love.filesystem.read('editor_support/runtime.lua'))
  return '-- Generated by Particle Studio. Copy gpuparticles/ beside this file.\n'..
    '-- local effect = require("effect").new(); effect:update(dt); effect:draw(); effect:release()\n'..
    'local Runtime=(function()\n'..runtime..'\nend)()\nlocal definition='..lua(doc)..
    '\nreturn {new=function() return Runtime.new(definition) end}\n'
end
function S.export(doc) return S.write('exports/'..S.slug(doc.name)..'.lua',S.exportSource(doc)) end
return S
